import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./data/**/*.{js,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#cfbcff",
        secondary: "#cdc0e9",
        tertiary: "#e7c365",
        background: "#050505",
        surface: "#141218",
        "surface-dim": "#141218",
        "surface-bright": "#3b383e",
        "surface-variant": "#36343a",
        "surface-container": "#211f24",
        "surface-container-low": "#1d1b20",
        "surface-container-high": "#2b292f",
        "surface-container-highest": "#36343a",
        "surface-container-lowest": "#0f0d13",
        "surface-tint": "#cfbcff",
        "on-surface": "#e6e0e9",
        "on-surface-variant": "#cbc4d2",
        "on-background": "#e6e0e9",
        "on-primary": "#381e72",
        "on-primary-container": "#e0d2ff",
        "on-secondary": "#342b4b",
        "on-secondary-container": "#bfb2da",
        "on-tertiary": "#3e2e00",
        "on-tertiary-container": "#503d00",
        "primary-container": "#6750a4",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#cfbcff",
        "on-primary-fixed": "#22005d",
        "on-primary-fixed-variant": "#4f378a",
        "secondary-container": "#4d4465",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#cdc0e9",
        "on-secondary-fixed": "#1f1635",
        "on-secondary-fixed-variant": "#4b4263",
        "tertiary-container": "#c9a74d",
        "tertiary-fixed": "#ffdf93",
        "tertiary-fixed-dim": "#e7c365",
        "on-tertiary-fixed-variant": "#594400",
        outline: "#948e9c",
        "outline-variant": "#494551",
        "inverse-surface": "#e6e0e9",
        "inverse-on-surface": "#322f35",
        "inverse-primary": "#6750a4",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "0.75rem",
      },
      fontFamily: {
        display: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
        pixel: ["var(--font-press-start)", "monospace"],
      },
      keyframes: {
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 10px rgba(207,188,255,0.3)" },
          "50%": { boxShadow: "0 0 25px rgba(207,188,255,0.6)" },
        },
      },
      animation: {
        blink: "blink 1s infinite",
        "fade-up": "fade-up 0.5s ease-out forwards",
        "glow-pulse": "glow-pulse 2.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
} satisfies Config;
